# Start dari image yang sudah ada Go dan Node
FROM mcr.microsoft.com/devcontainers/go:latest

# Konfigurasi Node.js (sebagai contoh)
RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g pnpm"