// services/goal-service/goal.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: services/goal-service/goal.proto

package goal_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pesan (Message) untuk Request
type CreateGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoalRequest) Reset() {
	*x = CreateGoalRequest{}
	mi := &file_services_goal_service_goal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoalRequest) ProtoMessage() {}

func (x *CreateGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_goal_service_goal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoalRequest.ProtoReflect.Descriptor instead.
func (*CreateGoalRequest) Descriptor() ([]byte, []int) {
	return file_services_goal_service_goal_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGoalRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateGoalRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoalId        int32                  `protobuf:"varint,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoalRequest) Reset() {
	*x = GetGoalRequest{}
	mi := &file_services_goal_service_goal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalRequest) ProtoMessage() {}

func (x *GetGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_goal_service_goal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalRequest.ProtoReflect.Descriptor instead.
func (*GetGoalRequest) Descriptor() ([]byte, []int) {
	return file_services_goal_service_goal_proto_rawDescGZIP(), []int{1}
}

func (x *GetGoalRequest) GetGoalId() int32 {
	if x != nil {
		return x.GoalId
	}
	return 0
}

// Pesan (Message) untuk Response/Model Data
type Goal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // Contoh: "active", "completed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goal) Reset() {
	*x = Goal{}
	mi := &file_services_goal_service_goal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goal) ProtoMessage() {}

func (x *Goal) ProtoReflect() protoreflect.Message {
	mi := &file_services_goal_service_goal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goal.ProtoReflect.Descriptor instead.
func (*Goal) Descriptor() ([]byte, []int) {
	return file_services_goal_service_goal_proto_rawDescGZIP(), []int{2}
}

func (x *Goal) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Goal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Goal) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Goal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_services_goal_service_goal_proto protoreflect.FileDescriptor

const file_services_goal_service_goal_proto_rawDesc = "" +
	"\n" +
	" services/goal-service/goal.proto\x12\fgoal_service\"B\n" +
	"\x11CreateGoalRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\")\n" +
	"\x0eGetGoalRequest\x12\x17\n" +
	"\agoal_id\x18\x01 \x01(\x05R\x06goalId\"]\n" +
	"\x04Goal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\x8d\x01\n" +
	"\vGoalService\x12A\n" +
	"\n" +
	"CreateGoal\x12\x1f.goal_service.CreateGoalRequest\x1a\x12.goal_service.Goal\x12;\n" +
	"\aGetGoal\x12\x1c.goal_service.GetGoalRequest\x1a\x12.goal_service.GoalB6Z4goal-tracking-app/services/goal-service;goal_serviceb\x06proto3"

var (
	file_services_goal_service_goal_proto_rawDescOnce sync.Once
	file_services_goal_service_goal_proto_rawDescData []byte
)

func file_services_goal_service_goal_proto_rawDescGZIP() []byte {
	file_services_goal_service_goal_proto_rawDescOnce.Do(func() {
		file_services_goal_service_goal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_goal_service_goal_proto_rawDesc), len(file_services_goal_service_goal_proto_rawDesc)))
	})
	return file_services_goal_service_goal_proto_rawDescData
}

var file_services_goal_service_goal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_goal_service_goal_proto_goTypes = []any{
	(*CreateGoalRequest)(nil), // 0: goal_service.CreateGoalRequest
	(*GetGoalRequest)(nil),    // 1: goal_service.GetGoalRequest
	(*Goal)(nil),              // 2: goal_service.Goal
}
var file_services_goal_service_goal_proto_depIdxs = []int32{
	0, // 0: goal_service.GoalService.CreateGoal:input_type -> goal_service.CreateGoalRequest
	1, // 1: goal_service.GoalService.GetGoal:input_type -> goal_service.GetGoalRequest
	2, // 2: goal_service.GoalService.CreateGoal:output_type -> goal_service.Goal
	2, // 3: goal_service.GoalService.GetGoal:output_type -> goal_service.Goal
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_goal_service_goal_proto_init() }
func file_services_goal_service_goal_proto_init() {
	if File_services_goal_service_goal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_goal_service_goal_proto_rawDesc), len(file_services_goal_service_goal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_goal_service_goal_proto_goTypes,
		DependencyIndexes: file_services_goal_service_goal_proto_depIdxs,
		MessageInfos:      file_services_goal_service_goal_proto_msgTypes,
	}.Build()
	File_services_goal_service_goal_proto = out.File
	file_services_goal_service_goal_proto_goTypes = nil
	file_services_goal_service_goal_proto_depIdxs = nil
}
